version: '3'
services:
  postgres:
    image: postgres:10
    container_name: pagpostgres
    command: ["-c", "max_connections=1000"]
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pixelart_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pa4sswo0rdb

  pag-api:
    build: ./pag-api
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
    depends_on:
      - postgres

  pag-wui:
    build: ./pag-wui
    ports:
      - '3000:3000'
