version: '3'
services:
  postgres:
    image: postgres:10
    container_name: pagpostgres
    command: ["-c", "max_connections=1000"]
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pixelart_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pa4sswo0rdb

  pag-api:
    build: ./pag-api
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - DB_CONNECTION=postgres
      # - DB_CONNECTION=pixelart-gen-db.cvnqyzh4r2cp.us-east-1.rds.amazonaws.com
    links:
      - "postgres:localhost"
    depends_on:
      - postgres

  # pag-wui:
  #   build: ./pag-wui
  #   links:
  #     - "pag-api:localhost"
  #   environment:
  #     - API_HOST=pag-api
  #   ports:
  #     - '3000:3000'
